// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usermeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersignMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersigncountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useridMw() []app.HandlerFunc {
	// your code...
	hlog.Info("Enter useridMw")
	return nil
}

func _usernumMw() []app.HandlerFunc {
	// your code...
	return nil
}
