version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # AMQP 端口，用于与 RabbitMQ 服务通信
      - "15672:15672"  # RabbitMQ Web 管理界面的端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # 默认用户
      - RABBITMQ_DEFAULT_PASS=guest  # 默认密码
  # 主节点（Master）
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - 6379:6379
    command: redis-server --requirepass password
    networks:
      - redis-net

  # 从节点（Slave）
  redis-slave:
    image: redis:latest
    container_name: redis-slave
    # 将宿主机的 6380 端口映射到容器的 6379 端口
    ports:
      - 6380:6379
    command: >
      redis-server
      --slaveof redis-master 6379
      --masterauth password
      --requirepass password
    depends_on:
      - redis-master
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge