version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # AMQP 端口，用于与 RabbitMQ 服务通信
      - "15672:15672"  # RabbitMQ Web 管理界面的端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # 默认用户
      - RABBITMQ_DEFAULT_PASS=guest  # 默认密码