version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # AMQP 端口，用于与 RabbitMQ 服务通信
      - "15672:15672"  # RabbitMQ Web 管理界面的端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # 默认用户
      - RABBITMQ_DEFAULT_PASS=guest  # 默认密码
  # Redis 主节点
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - 6379:6379
    command: redis-server --requirepass password --masterauth password
    networks:
      - redis-net

  # Redis 从节点 1
  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - 6380:6379
    command: >
      redis-server
      --requirepass password
      --masterauth password
      --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  # Redis 从节点 2
  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - 6381:6379
    command: >
      redis-server
      --requirepass password
      --masterauth password
      --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  # 哨兵节点 1
  redis-sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    ports:
      - 26379:26379
    command: >
      redis-server /data/redis/sentinel1.conf --sentinel
    volumes:
      - ./sentinel_conf/sentinel1:/data/redis
    networks:
      - redis-net

  # 哨兵节点 2
  redis-sentinel2:
    image: redis:latest
    container_name: redis-sentinel2
    ports:
      - 26380:26379
    command: >
      redis-server /data/redis/sentinel2.conf --sentinel
    volumes:
      - ./sentinel_conf/sentinel2:/data/redis
    networks:
      - redis-net

  # 哨兵节点 3
  redis-sentinel3:
    image: redis:latest
    container_name: redis-sentinel3
    ports:
      - 26381:26379
    command: >
      redis-server /data/redis/sentinel3.conf --sentinel
    volumes:
      - ./sentinel_conf/sentinel3/:/data/redis
    networks:
      - redis-net



networks:
  redis-net:
    driver: bridge