// Code generated by hertz generator.

package voucher

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _voucherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _voucherlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _voucher_orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _seckillMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _seckillvoucherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createvoucherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createseckillvoucherMw() []app.HandlerFunc {
	// your code...
	return nil
}
